FROM node:14-alpine

USER dash_sv
WORKDIR /dashboard

ADD ./src /dashboard/src
ADD ./package-lock.json /dashboard/package-lock.json
ADD ./package.json /dashboard/package.json
ADD ./config /dashboard/config
ADD ./data /dashboard/data

RUN npm ci

ENV NODE_ENV=prod
ENV WS_PORT=3030

EXPOSE 3030

CMD ["npm", "start"]